// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: ap.proto

package ap

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	co "github.com/zhoubowen-sky/zpb/co"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query   string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNum int32  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	Cccc    *co.Cm `protobuf:"bytes,3,opt,name=cccc,proto3" json:"cccc,omitempty"`
}

func (x *SaReq) Reset() {
	*x = SaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaReq) ProtoMessage() {}

func (x *SaReq) ProtoReflect() protoreflect.Message {
	mi := &file_ap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaReq.ProtoReflect.Descriptor instead.
func (*SaReq) Descriptor() ([]byte, []int) {
	return file_ap_proto_rawDescGZIP(), []int{0}
}

func (x *SaReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SaReq) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *SaReq) GetCccc() *co.Cm {
	if x != nil {
		return x.Cccc
	}
	return nil
}

type SaRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Pia    *co.Pia `protobuf:"bytes,2,opt,name=pia,proto3" json:"pia,omitempty"`
}

func (x *SaRsp) Reset() {
	*x = SaRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaRsp) ProtoMessage() {}

func (x *SaRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaRsp.ProtoReflect.Descriptor instead.
func (*SaRsp) Descriptor() ([]byte, []int) {
	return file_ap_proto_rawDescGZIP(), []int{1}
}

func (x *SaRsp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SaRsp) GetPia() *co.Pia {
	if x != nil {
		return x.Pia
	}
	return nil
}

var File_ap_proto protoreflect.FileDescriptor

var file_ap_proto_rawDesc = []byte{
	0x0a, 0x08, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x7a, 0x70, 0x62, 0x2e,
	0x61, 0x70, 0x1a, 0x08, 0x63, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x05,
	0x53, 0x61, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70,
	0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x63, 0x63, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x7a, 0x70, 0x62, 0x2e, 0x63, 0x6f, 0x2e, 0x43, 0x6d,
	0x52, 0x04, 0x63, 0x63, 0x63, 0x63, 0x22, 0x3e, 0x0a, 0x05, 0x53, 0x61, 0x52, 0x73, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x03, 0x70, 0x69, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x7a, 0x70, 0x62, 0x2e, 0x63, 0x6f, 0x2e, 0x50, 0x69,
	0x61, 0x52, 0x03, 0x70, 0x69, 0x61, 0x32, 0x31, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x61, 0x61, 0x12, 0x23, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0d, 0x2e, 0x7a, 0x70,
	0x62, 0x2e, 0x61, 0x70, 0x2e, 0x53, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x7a, 0x70, 0x62,
	0x2e, 0x61, 0x70, 0x2e, 0x53, 0x61, 0x52, 0x73, 0x70, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x6f, 0x75, 0x62, 0x6f, 0x77, 0x65,
	0x6e, 0x2d, 0x73, 0x6b, 0x79, 0x2f, 0x7a, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ap_proto_rawDescOnce sync.Once
	file_ap_proto_rawDescData = file_ap_proto_rawDesc
)

func file_ap_proto_rawDescGZIP() []byte {
	file_ap_proto_rawDescOnce.Do(func() {
		file_ap_proto_rawDescData = protoimpl.X.CompressGZIP(file_ap_proto_rawDescData)
	})
	return file_ap_proto_rawDescData
}

var file_ap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ap_proto_goTypes = []interface{}{
	(*SaReq)(nil),  // 0: zpb.ap.SaReq
	(*SaRsp)(nil),  // 1: zpb.ap.SaRsp
	(*co.Cm)(nil),  // 2: zpb.co.Cm
	(*co.Pia)(nil), // 3: zpb.co.Pia
}
var file_ap_proto_depIdxs = []int32{
	2, // 0: zpb.ap.SaReq.cccc:type_name -> zpb.co.Cm
	3, // 1: zpb.ap.SaRsp.pia:type_name -> zpb.co.Pia
	0, // 2: zpb.ap.ServiceSaa.Get:input_type -> zpb.ap.SaReq
	1, // 3: zpb.ap.ServiceSaa.Get:output_type -> zpb.ap.SaRsp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ap_proto_init() }
func file_ap_proto_init() {
	if File_ap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ap_proto_goTypes,
		DependencyIndexes: file_ap_proto_depIdxs,
		MessageInfos:      file_ap_proto_msgTypes,
	}.Build()
	File_ap_proto = out.File
	file_ap_proto_rawDesc = nil
	file_ap_proto_goTypes = nil
	file_ap_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceSaaClient is the client API for ServiceSaa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceSaaClient interface {
	Get(ctx context.Context, in *SaReq, opts ...grpc.CallOption) (*SaRsp, error)
}

type serviceSaaClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceSaaClient(cc grpc.ClientConnInterface) ServiceSaaClient {
	return &serviceSaaClient{cc}
}

func (c *serviceSaaClient) Get(ctx context.Context, in *SaReq, opts ...grpc.CallOption) (*SaRsp, error) {
	out := new(SaRsp)
	err := c.cc.Invoke(ctx, "/zpb.ap.ServiceSaa/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceSaaServer is the server API for ServiceSaa service.
type ServiceSaaServer interface {
	Get(context.Context, *SaReq) (*SaRsp, error)
}

// UnimplementedServiceSaaServer can be embedded to have forward compatible implementations.
type UnimplementedServiceSaaServer struct {
}

func (*UnimplementedServiceSaaServer) Get(context.Context, *SaReq) (*SaRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterServiceSaaServer(s *grpc.Server, srv ServiceSaaServer) {
	s.RegisterService(&_ServiceSaa_serviceDesc, srv)
}

func _ServiceSaa_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceSaaServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zpb.ap.ServiceSaa/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceSaaServer).Get(ctx, req.(*SaReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceSaa_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zpb.ap.ServiceSaa",
	HandlerType: (*ServiceSaaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ServiceSaa_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ap.proto",
}
